
import { Country } from './types';

export const asianCountries: Country[] = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫" },
  { code: "AM", name: "Armenia", flag: "🇦🇲" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭" },
  { code: "BN", name: "Brunei Darussalam", flag: "🇧🇳" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹" },
  { code: "CN", name: "China", flag: "🇨🇳" },
  { code: "GE", name: "Georgia", flag: "🇬🇪" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "IR", name: "Iran", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶" },
  { code: "IL", name: "Israel", flag: "🇮🇱" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "JO", name: "Jordan", flag: "🇯🇴" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭" },
  { code: "KP", name: "Korea, Democratic People's Republic of", flag: "🇰🇵" },
  { code: "KR", name: "Korea, Republic of", flag: "🇰🇷" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
  { code: "LA", name: "Lao People's Democratic Republic", flag: "🇱🇦" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳" },
  { code: "MO", name: "Macao", flag: "🇲🇴" },
  { code: "MV", name: "Maldives", flag: "🇲🇻" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾" },
  { code: "NP", name: "Nepal", flag: "🇳🇵" },
  { code: "OM", name: "Oman", flag: "🇴🇲" },
  { code: "PH", name: "Philippines", flag: "🇵🇭" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰" },
  { code: "PS", name: "Palestine, State of", flag: "🇵🇸" },
  { code: "QA", name: "Qatar", flag: "🇶🇦" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "SG", name: "Singapore", flag: "🇸🇬" },
  { code: "SY", name: "Syrian Arab Republic", flag: "🇸🇾" },
  { code: "TH", name: "Thailand", flag: "🇹🇭" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯" },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  { code: "YE", name: "Yemen", flag: "🇾🇪" }
];
